// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_motifs_cpp
List find_motifs_cpp(std::string sequence, List params_list);
RcppExport SEXP _nonBgfa_find_motifs_cpp(SEXP sequenceSEXP, SEXP params_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type sequence(sequenceSEXP);
    Rcpp::traits::input_parameter< List >::type params_list(params_listSEXP);
    rcpp_result_gen = Rcpp::wrap(find_motifs_cpp(sequence, params_list));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nonBgfa_find_motifs_cpp", (DL_FUNC) &_nonBgfa_find_motifs_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_nonBgfa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
