# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_motifs_cpp <- function(sequence, params_list) {
    .Call(`_nonBgfa_find_motifs_cpp`, sequence, params_list)
}

